version: '3'
services:
  flask-app:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8888:8888'
    volumes:
      - database:/app/db
    env_file:
      - .env
  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'

volumes:
  database: